spring.application.name=customers-service

spring.config.import=configserver:http://config-server:8888

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=3000
spring.cloud.config.retry.multiplier=1.5

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

management.endpoints.web.exposure.include=*