spring.application.name=inventory-service

spring.config.import=optional:configserver:http://config-server:8888

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
